version: '2'
volumes:
  resin-data:
services:
  nats-streaming-server:
    restart: always
    build: ./nats-streaming-server
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - 'resin-data:/data'
#  influxdb:
#    restart: always
#    build: ./influxdb
#    volumes:
#      - 'resin-data:/data'
#  grafana:
#    restart: always
#    build: ./grafana
#    ports:
#      - "80:3000"
#    volumes:
#      - 'resin-data:/data'
